"""initial schema

Revision ID: 0001
Revises: (base)
Create Date: 2026-08-14 09:29:32.408852
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "active",
                "suspended",
                "disabled",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("sequence_number", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "user",
                "system",
                "agent",
                name="audit_log_actor_type",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        sa.UniqueConstraint("sequence_number", name=op.f("uq_audit_logs_sequence_number")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_type"), "audit_logs", ["actor_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_entity_type_entity_id",
        "audit_logs",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_organization_id_sequence",
        "audit_logs",
        ["organization_id", "sequence_number"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_table(
        "disclosure_policies",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("ai_disclosure_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("ai_disclosure_text", sa.Text(), nullable=False),
        sa.Column(
            "advertising_disclosure_required", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("advertising_disclosure_text", sa.Text(), nullable=False),
        sa.Column(
            "requires_high_risk_approval", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_disclosure_policies_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disclosure_policies")),
        sa.UniqueConstraint(
            "organization_id", "code", name="uq_disclosure_policies_organization_id_code"
        ),
    )
    op.create_index(
        op.f("ix_disclosure_policies_created_at"),
        "disclosure_policies",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_disclosure_policies_organization_id"),
        "disclosure_policies",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "creative_lead",
                "operator",
                "reviewer",
                "compliance",
                "analyst",
                "agent",
                name="membership_role",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memberships_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_memberships_organization_id_user_id"
        ),
    )
    op.create_index(op.f("ix_memberships_created_at"), "memberships", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "influencers",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("public_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "archived",
                name="influencer_status",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("niche", sa.String(length=200), nullable=True),
        sa.Column("primary_language", sa.String(length=16), nullable=False),
        sa.Column("primary_market", sa.String(length=16), nullable=False),
        sa.Column(
            "adult_representation_confirmed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("disclosure_policy_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["disclosure_policy_id"],
            ["disclosure_policies.id"],
            name=op.f("fk_influencers_disclosure_policy_id_disclosure_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_influencers_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_influencers")),
        sa.UniqueConstraint("organization_id", "code", name="uq_influencers_organization_id_code"),
    )
    op.create_index(op.f("ix_influencers_code"), "influencers", ["code"], unique=False)
    op.create_index(op.f("ix_influencers_created_at"), "influencers", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_influencers_disclosure_policy_id"),
        "influencers",
        ["disclosure_policy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_influencers_organization_id"), "influencers", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_influencers_status"), "influencers", ["status"], unique=False)
    op.create_table(
        "influencer_versions",
        sa.Column("influencer_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=False),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("tone_of_voice", sa.Text(), nullable=True),
        sa.Column("personality_traits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prohibited_topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("visual_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("speech_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_influencer_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_influencer_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["influencer_id"],
            ["influencers.id"],
            name=op.f("fk_influencer_versions_influencer_id_influencers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_influencer_versions")),
        sa.UniqueConstraint(
            "influencer_id",
            "version_number",
            name="uq_influencer_versions_influencer_id_version_number",
        ),
    )
    op.create_index(
        op.f("ix_influencer_versions_created_at"),
        "influencer_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_influencer_versions_influencer_id"),
        "influencer_versions",
        ["influencer_id"],
        unique=False,
    )
    op.create_index(
        "uq_influencer_versions_influencer_id_current",
        "influencer_versions",
        ["influencer_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_influencer_versions_influencer_id_current",
        table_name="influencer_versions",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(op.f("ix_influencer_versions_influencer_id"), table_name="influencer_versions")
    op.drop_index(op.f("ix_influencer_versions_created_at"), table_name="influencer_versions")
    op.drop_table("influencer_versions")
    op.drop_index(op.f("ix_influencers_status"), table_name="influencers")
    op.drop_index(op.f("ix_influencers_organization_id"), table_name="influencers")
    op.drop_index(op.f("ix_influencers_disclosure_policy_id"), table_name="influencers")
    op.drop_index(op.f("ix_influencers_created_at"), table_name="influencers")
    op.drop_index(op.f("ix_influencers_code"), table_name="influencers")
    op.drop_table("influencers")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_created_at"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_disclosure_policies_organization_id"), table_name="disclosure_policies")
    op.drop_index(op.f("ix_disclosure_policies_created_at"), table_name="disclosure_policies")
    op.drop_table("disclosure_policies")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_organization_id_sequence", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity_type_entity_id", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
